name = "fphov-dashboard"
compatibility_date = "2026-05-27"

# This is the key for Pages
pages_build_output_dir = "."

# KV binding (this part is good and important)
[[kv_namespaces]]
binding = "FPHOV_AUTH"
id = "1cbc13719f444bcb83975b12301e3d7e"
